insert into customers (customer_id, first_name, last_name, address) values (1, 'Shepperd', 'Burkert', '5 Sachs Way');
insert into customers (customer_id, first_name, last_name, address) values (2, 'Michaela', 'Questier', '1085 American Ash Circle');
insert into customers (customer_id, first_name, last_name, address) values (3, 'Beck', 'Frye', '7979 Forest Dale Center');
insert into customers (customer_id, first_name, last_name, address) values (4, 'Julian', 'Dunster', '93349 Forster Center');
insert into customers (customer_id, first_name, last_name, address) values (5, 'Grayce', 'Blazejewski', '3284 Talmadge Crossing');
insert into customers (customer_id, first_name, last_name, address) values (6, 'Zea', 'Wilde', '2 Elgar Way');
insert into customers (customer_id, first_name, last_name, address) values (7, 'Katha', 'Rawsthorne', '19512 Fallview Trail');
insert into customers (customer_id, first_name, last_name, address) values (8, 'Erl', 'Crewther', '583 Northfield Place');
insert into customers (customer_id, first_name, last_name, address) values (9, 'Gayelord', 'Munslow', '8 Logan Avenue');
insert into customers (customer_id, first_name, last_name, address) values (10, 'Karlens', 'Chinnery', '55 Comanche Lane');
insert into customers (customer_id, first_name, last_name, address) values (11, 'Lauren', 'Werndley', '3 Susan Junction');
insert into customers (customer_id, first_name, last_name, address) values (12, 'Carmon', 'Corbett', '85813 Fordem Pass');
insert into customers (customer_id, first_name, last_name, address) values (13, 'Lisle', 'Witterick', '2658 Londonderry Parkway');
insert into customers (customer_id, first_name, last_name, address) values (14, 'Glen', 'Rockwill', '23 Morrow Way');
insert into customers (customer_id, first_name, last_name, address) values (15, 'Natal', 'Abrahami', '4634 Briar Crest Junction');
insert into customers (customer_id, first_name, last_name, address) values (16, 'Aidan', 'Plues', '135 Magdeline Trail');
insert into customers (customer_id, first_name, last_name, address) values (17, 'Fonz', 'Bison', '0689 Blackbird Plaza');
insert into customers (customer_id, first_name, last_name, address) values (18, 'Lizette', 'Mourbey', '8 Warbler Center');
insert into customers (customer_id, first_name, last_name, address) values (19, 'Danila', 'Argile', '9 Stuart Lane');
insert into customers (customer_id, first_name, last_name, address) values (20, 'Bevin', 'Scoullar', '273 Redwing Pass');
insert into customers (customer_id, first_name, last_name, address) values (21, 'Ediva', 'Greenstead', '72694 Northland Trail');
insert into customers (customer_id, first_name, last_name, address) values (22, 'Freeman', 'Vala', '3 School Road');
insert into customers (customer_id, first_name, last_name, address) values (23, 'Sig', 'Bellanger', '29 Manley Center');
insert into customers (customer_id, first_name, last_name, address) values (24, 'Ethelred', 'Elderbrant', '17452 Cody Center');
insert into customers (customer_id, first_name, last_name, address) values (25, 'Frans', 'Filasov', '39698 Emmet Lane');
insert into customers (customer_id, first_name, last_name, address) values (26, 'Melantha', 'Duff', '55 Lindbergh Court');
insert into customers (customer_id, first_name, last_name, address) values (27, 'Perkin', 'Hullin', '446 Redwing Drive');
insert into customers (customer_id, first_name, last_name, address) values (28, 'Josi', 'Birtle', '1 Delladonna Trail');
insert into customers (customer_id, first_name, last_name, address) values (29, 'Merell', 'Belfitt', '0914 Magdeline Terrace');
insert into customers (customer_id, first_name, last_name, address) values (30, 'Tierney', 'Godfray', '462 Hintze Trail');
insert into customers (customer_id, first_name, last_name, address) values (31, 'Iago', 'Scawton', '82851 Ridgeview Alley');
insert into customers (customer_id, first_name, last_name, address) values (32, 'Monika', 'Odlin', '15 Manufacturers Road');
insert into customers (customer_id, first_name, last_name, address) values (33, 'Kimberlee', 'Izkovicz', '9 8th Avenue');
insert into customers (customer_id, first_name, last_name, address) values (34, 'Maxie', 'Mackerness', '70102 Katie Circle');
insert into customers (customer_id, first_name, last_name, address) values (35, 'Devy', 'Wildbore', '58 Bunting Hill');
insert into customers (customer_id, first_name, last_name, address) values (36, 'Olivier', 'Codron', '7254 Nova Crossing');
insert into customers (customer_id, first_name, last_name, address) values (37, 'Kathi', 'Fosken', '3494 Transport Way');
insert into customers (customer_id, first_name, last_name, address) values (38, 'Sapphira', 'Scanlin', '46770 Cardinal Terrace');
insert into customers (customer_id, first_name, last_name, address) values (39, 'Timofei', 'Hurford', '1303 Ruskin Circle');
insert into customers (customer_id, first_name, last_name, address) values (40, 'Julio', 'Menault', '25 Montana Junction');
insert into customers (customer_id, first_name, last_name, address) values (41, 'Andros', 'Bedham', '4 Anzinger Trail');
insert into customers (customer_id, first_name, last_name, address) values (42, 'Anabella', 'Cowdroy', '4 Badeau Crossing');
insert into customers (customer_id, first_name, last_name, address) values (43, 'Virginia', 'Summers', '903 Vahlen Junction');
insert into customers (customer_id, first_name, last_name, address) values (44, 'Quinton', 'Kitson', '7 Graceland Street');
insert into customers (customer_id, first_name, last_name, address) values (45, 'Claudian', 'Beardsworth', '77787 Roxbury Avenue');
insert into customers (customer_id, first_name, last_name, address) values (46, 'Lyndell', 'McAlpin', '3 Anzinger Lane');
insert into customers (customer_id, first_name, last_name, address) values (47, 'Lynett', 'Corbett', '83441 Paget Avenue');
insert into customers (customer_id, first_name, last_name, address) values (48, 'Linc', 'Papachristophorou', '4 Dorton Terrace');
insert into customers (customer_id, first_name, last_name, address) values (49, 'Lenee', 'Sanbrook', '3999 Norway Maple Crossing');
insert into customers (customer_id, first_name, last_name, address) values (50, 'Lisle', 'Pollen', '46643 Morning Court');
insert into customers (customer_id, first_name, last_name, address) values (51, 'Genvieve', 'Reading', '32 Walton Trail');
insert into customers (customer_id, first_name, last_name, address) values (52, 'Joli', 'Seear', '102 Schmedeman Avenue');
insert into customers (customer_id, first_name, last_name, address) values (53, 'Monroe', 'Schoffel', '065 Welch Point');
insert into customers (customer_id, first_name, last_name, address) values (54, 'Rafe', 'Shillington', '49312 Nevada Way');
insert into customers (customer_id, first_name, last_name, address) values (55, 'Gigi', 'McMorran', '79663 Dixon Point');
insert into customers (customer_id, first_name, last_name, address) values (56, 'Bethany', 'Lund', '27774 Manitowish Road');
insert into customers (customer_id, first_name, last_name, address) values (57, 'Phillida', 'Sterricker', '53846 Badeau Way');
insert into customers (customer_id, first_name, last_name, address) values (58, 'Cathie', 'MacTavish', '07026 Grayhawk Terrace');
insert into customers (customer_id, first_name, last_name, address) values (59, 'Reggi', 'Liston', '1637 Quincy Center');
insert into customers (customer_id, first_name, last_name, address) values (60, 'Serene', 'O''Dare', '8 Holy Cross Way');
insert into customers (customer_id, first_name, last_name, address) values (61, 'Ulrikaumeko', 'Goodboddy', '4185 Elmside Street');
insert into customers (customer_id, first_name, last_name, address) values (62, 'Wren', 'Kiernan', '6 Bobwhite Court');
insert into customers (customer_id, first_name, last_name, address) values (63, 'Hester', 'Randlesome', '79272 Porter Center');
insert into customers (customer_id, first_name, last_name, address) values (64, 'Amitie', 'Bernadot', '5 Gerald Parkway');
insert into customers (customer_id, first_name, last_name, address) values (65, 'Larina', 'Cattermole', '99909 Hanover Center');
insert into customers (customer_id, first_name, last_name, address) values (66, 'Elinor', 'Gable', '29335 Hoffman Alley');
insert into customers (customer_id, first_name, last_name, address) values (67, 'Morgana', 'Rainforth', '987 Northfield Drive');
insert into customers (customer_id, first_name, last_name, address) values (68, 'Franny', 'Di Bernardo', '352 Burrows Road');
insert into customers (customer_id, first_name, last_name, address) values (69, 'Rooney', 'Veall', '12339 7th Point');
insert into customers (customer_id, first_name, last_name, address) values (70, 'Alexander', 'Trebble', '33386 Mcbride Pass');
insert into customers (customer_id, first_name, last_name, address) values (71, 'Waverly', 'Brotherheed', '93380 Almo Circle');
insert into customers (customer_id, first_name, last_name, address) values (72, 'Penny', 'Toby', '13 Hollow Ridge Terrace');
insert into customers (customer_id, first_name, last_name, address) values (73, 'Merrilee', 'Sarl', '9 Blackbird Park');
insert into customers (customer_id, first_name, last_name, address) values (74, 'Shawn', 'Oganesian', '825 Saint Paul Crossing');
insert into customers (customer_id, first_name, last_name, address) values (75, 'Cathie', 'Peres', '2 Fuller Park');
insert into customers (customer_id, first_name, last_name, address) values (76, 'Eleni', 'Libermore', '07 Novick Junction');
insert into customers (customer_id, first_name, last_name, address) values (77, 'Tyne', 'Nesfield', '3 Laurel Pass');
insert into customers (customer_id, first_name, last_name, address) values (78, 'Loralie', 'Gibbe', '995 Kensington Parkway');
insert into customers (customer_id, first_name, last_name, address) values (79, 'Onfroi', 'Heugh', '0 Stoughton Way');
insert into customers (customer_id, first_name, last_name, address) values (80, 'Rogerio', 'Abrahami', '20144 Becker Avenue');
insert into customers (customer_id, first_name, last_name, address) values (81, 'Timothy', 'Hoxey', '69 Huxley Way');
insert into customers (customer_id, first_name, last_name, address) values (82, 'Elna', 'Smeeth', '6 Meadow Valley Alley');
insert into customers (customer_id, first_name, last_name, address) values (83, 'Clareta', 'Iskow', '756 Cascade Street');
insert into customers (customer_id, first_name, last_name, address) values (84, 'Wolf', 'Seson', '436 Ronald Regan Junction');
insert into customers (customer_id, first_name, last_name, address) values (85, 'Glennie', 'Kira', '0394 Texas Parkway');
insert into customers (customer_id, first_name, last_name, address) values (86, 'Eben', 'Linturn', '49594 Bluejay Circle');
insert into customers (customer_id, first_name, last_name, address) values (87, 'Frannie', 'Coult', '726 Emmet Drive');
insert into customers (customer_id, first_name, last_name, address) values (88, 'Gus', 'Yanshinov', '0 Amoth Parkway');
insert into customers (customer_id, first_name, last_name, address) values (89, 'Kenton', 'Bleakley', '1 Warbler Way');
insert into customers (customer_id, first_name, last_name, address) values (90, 'Elissa', 'Olenchenko', '212 Northport Junction');
insert into customers (customer_id, first_name, last_name, address) values (91, 'Fianna', 'Corkel', '642 Anhalt Avenue');
insert into customers (customer_id, first_name, last_name, address) values (92, 'Garret', 'Paulig', '79 Northland Point');
insert into customers (customer_id, first_name, last_name, address) values (93, 'Moira', 'Hadeke', '7 Hayes Park');
insert into customers (customer_id, first_name, last_name, address) values (94, 'Matthieu', 'Pratchett', '1724 Morrow Hill');
insert into customers (customer_id, first_name, last_name, address) values (95, 'Madelon', 'Nuccii', '0 Gulseth Point');
insert into customers (customer_id, first_name, last_name, address) values (96, 'Brice', 'Trafford', '044 Starling Court');
insert into customers (customer_id, first_name, last_name, address) values (97, 'Krispin', 'Skipping', '1846 Dakota Lane');
insert into customers (customer_id, first_name, last_name, address) values (98, 'Carmella', 'Magson', '8666 Susan Park');
insert into customers (customer_id, first_name, last_name, address) values (99, 'Sibel', 'Manntschke', '98027 Dayton Junction');
insert into customers (customer_id, first_name, last_name, address) values (100, 'Leanna', 'Slorach', '3908 Lukken Plaza');
